= Introduction
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:sourcedir: .

[[_manual_overview]]
== What this guide covers

This guide covers all aspects of Spring Web Flow.
It covers implementing flows in end-user applications and working with the feature set.
It also covers extending the framework and the overall architectural model. 

[[_system_requirements]]
== What Web Flow requires to run

Java 1.8 or higher. 

Spring 5.0 or higher. 

== Resources

You can ask questions and interact on StackOverflow using the designated tags, see https://spring.io/questions[Spring at StackOverflow]. 

Report bugs and make requests using the https://jira.spring.io[Spring Issue Tracker]. 

Submit pull requests and work with the source code  , see https://github.com/spring-projects/spring-webflow[Web Flow on Github]. 

[[_jars_mvn_central]]
== How to access Web Flow artifacts from Maven Central

Each jar in the Web Flow distribution is available in the https://search.maven.org[Maven Central Repository].
This allows you to easily integrate Web Flow into your application if you are already using Maven as the build system for your web development project. 

To access Web Flow jars from Maven Central, declare the following dependency in your pom: 

[source,xml]
----

<dependency>
    <groupId>org.springframework.webflow</groupId>
    <artifactId>spring-webflow</artifactId>
    <version>x.y.z.RELEASE</version>
</dependency>
----

If using JavaServer Faces, declare the following dependency in your pom (includes transitive dependencies "spring-binding", "spring-webflow"): 

[source,xml]
----

<dependency>
    <groupId>org.springframework.webflow</groupId>
    <artifactId>spring-faces</artifactId>
    <version>x.y.z.RELEASE</version>
</dependency>
----

== How to access nightly builds and milestone releases

Nightly snapshots of Web Flow development branches are available using Maven.
These snapshot builds are useful for testing out fixes you depend on in advance of the next release, and provide a convenient way for you to provide feedback about whether a fix meets your needs. 

=== Accessing snapshots and milestones with Maven

For milestones and snapshots you'll need to use the SpringSource repository.
Add the following repository to your Maven pom.xml: 

[source,xml]
----

<repository>
    <id>spring</id>
    <name>Spring Repository</name>
    <url>https://repo.spring.io/snapshot</url>
</repository>
----

Then declare the following dependencies: 

[source,xml]
----

<dependency>
    <groupId>org.springframework.webflow</groupId>
    <artifactId>spring-webflow</artifactId>
    <version>x.y.z.BUILD-SNAPSHOT</version>
</dependency>
----

And if using JSF: 

[source,xml]
----

<dependency>
    <groupId>org.springframework.webflow</groupId>
    <artifactId>spring-faces</artifactId>
    <version>x.y.z.BUILD-SNAPSHOT</version>
</dependency>
----